
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-10
owner: ucsb-cs156-s25
repo_name: team02-s25-10
pull_requests: [{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-create-UCSBDiningCommonsMenuItemFixtures","number":68,"title":"Ac create ucsb dining commons menu item fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/68"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-review-form","number":67,"title":"Mh review form","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/67"},{"author":{"id":"U_kgDODELbWw","is_bot":false,"login":"bensoo777","name":""},"headRefName":"Ben-UCSBOrganization-organization-form","number":66,"title":"bs - add form for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/66"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-copy-backend-for-UCSBDiningCommonsMenuItem","number":65,"title":"ac - copy backend CRUD operations from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/65"},{"author":{"id":"U_kgDODELbWw","is_bot":false,"login":"bensoo777","name":""},"headRefName":"Ben-UCSBOrganization-commit-fixtures","number":64,"title":"bs - create fixtures for commit table","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/64"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-review-fixtures","number":63,"title":"Mh review fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/63"},{"author":{"id":"U_kgDODELbWw","is_bot":false,"login":"bensoo777","name":""},"headRefName":"Ben-UCSBOrganization-add-team01-files","number":62,"title":"bs - Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/62"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-copy-backend-for-reviews","number":61,"title":"mh - copied backend CRUD operations from team01 for the reviews table","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/61"}]
