
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-10
owner: ucsb-cs156-s25
repo_name: team02-s25-10
pull_requests: [{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-pages","number":96,"title":"Articles pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/96"},{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-placeholder","number":95,"title":"Articles placeholder","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/95"},{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-table","number":94,"title":"Articles table","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/94"},{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-forms","number":93,"title":"Articles forms","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/93"},{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-fixtures","number":84,"title":"Articles fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/84"},{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"articles-backend","number":83,"title":"finished backend","url":"https://github.com/ucsb-cs156-s25/team02-s25-10/pull/83"}]
